### ISSUE TITLE
Error after running Next example.

### ISSUE THREAD

**Issue by rickyrauch** [giuseppeg/styled-jsx-postcss#7]
Hello, I'd like to try this lib but I'm getting this error
```500
Internal Server Error.
Error in ./pages/index.js?entry
Module build failed: TypeError: unknown: Duplicate declaration "_JSXStyle"
  1 | import _JSXStyle from 'styled-jsx/style';
  2 | import React from 'react';
> 3 | import _JSXStyle from 'styled-jsx/style';
    |        ^
  4 | export default (function () {
  5 |   return React.createElement(
  6 |     'div',
    at File.buildCodeFrameError (/Users/ricardorauch/Sites/with-styled-jsx-postcss/node_modules/babel-core/lib/transformation/file/index.js:431:15)
    at Scope.checkBlockScopedCollisions (/Users/ricardorauch/Sites/with-styled-jsx-postcss/node_modules/babel-traverse/lib/scope/index.js:402:27)
    at Scope.registerBinding (/Users/ricardorauch/Sites/with-styled-jsx-postcss/node_modules/babel-traverse/lib/scope/index.js:596:16)
    at Scope.registerDeclaration (/Users/ricardorauch/Sites/with-styled-jsx-postcss/node_modules/babel-traverse/lib/scope/index.js:520:14)
    at Object.Declaration (/Users/ricardorauch/Sites/with-styled-jsx-postcss/node_modules/babel-traverse/lib/scope/index.js:176:36)
    at NodePath._call (/Users/ricardorauch/Sites/with-styled-jsx-postcss/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/ricardorauch/Sites/with-styled-jsx-postcss/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/ricardorauch/Sites/with-styled-jsx-postcss/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/ricardorauch/Sites/with-styled-jsx-postcss/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/ricardorauch/Sites/with-styled-jsx-postcss/node_modules/babel-traverse/lib/context.js:103:17)```

**Comment by giuseppeg** [comment]
see #10
